### ISSUE TITLE
New feature suggestion: Overwrite packages

### ISSUE THREAD

**Issue by jieey1140** [0x80/isolate-package#103]
While developing the electron app this time, I used a solution called “toDesktop” and what happened was that it tried to install all the dependencies. 

So I thought of adding some isolate features like overwriteDevDependencies and overwriteDependencies. 

For example

“overwriteDevDependencies": {
 “@electron-forge/cli": “6.4.2”,
}

This will remove the devDependencies in package.json except for the packages specified above. 

If you want to use the version of the package in the package.json, but keep the existing version, you can do it this way. 

“overwriteDevDependencies": { 
 “@electron-forge/cli": “sync”,
}

As above, you can design it to fetch the existing version when you work with it. 

I'm curious what you think of this new feature idea. If it's a good idea, I'd like to pull request a new feature on isolate. :smile:

**Comment by 0x80** [comment]
Sorry, I don't understand the problem you're describing here, so I have many questions.

> While developing the electron app this time, I used a solution called “toDesktop” and what happened was that it tried to install all the dependencies.

What's "it" and why are the dependencies listed in the manifest not what should be installed? 

What is the behavior you would expect for an Electron app? 

If you want to bundle all dependencies for desktop, shouldn't you use a bundler instead? What is the reason you chose to use isolate-package?
