### ISSUE TITLE
No binaries found in isolate / Failed to detect package manager

### ISSUE THREAD

**Issue by midrizi** [0x80/isolate-package#11]
Ran `pnpx isolate` and getting the following error:

> .../Library/pnpm/store/v3/tmp/dlx-4070   |   +1 +
 ERR_PNPM_DLX_NO_BIN  No binaries found in isolate
.../Library/pnpm/store/v3/tmp/dlx-4070   | Progress: resolved 1, reused 0, downloaded 0, added 0

Running `pnpm isolate` or `npx isolate`

> error Error: Failed to detect package manager
    at detectPackageManager (file:///ROOT/node_modules/.pnpm/isolate-package@1.1.1/node_modules/isolate-package/src/helpers/detect-package-manager.ts:19:9)
    at start (file:///ROOT/node_modules/.pnpm/isolate-package@1.1.1/node_modules/isolate-package/src/index.ts:59:26)

Folder structure:
```
apps
└─ native
   ├─ package.json
   └─ .eslintrc.js
packages
└─ eslint-config-custom
   ├─ index.js
   └─ package.json
functions
├─ lib/index.js
├─ firebase.json
├─ tsconfig.json
└─ package.json
```

**Comment by 0x80** [comment]
I find it a little odd that you have "apps" and "packages", but "functions" as a package is not part of any of them. 

I personally use a third category in my monorepo called "services" and then "functions" is inside of that. I think isolate-package [might expect each package to live in a folder that is declared as containing packages](https://github.com/0x80/isolate-package/#use-a-flat-structure-inside-your-packages-folders) 

What configuration do you use to declare your packages in the workspace?
