### ISSUE TITLE
Question: Still unclear how to setup my firebase in turborepo.

### ISSUE THREAD

**Issue by matallui** [0x80/isolate-package#21]
Hi! First of all, thank you for putting this together! It looks like a very useful tool, especially when it comes to using Firebase with monorepos.

I'll be honest, this is the first time I'm working with Firebase, so the experience there isn't much, but I do have a good understanding of Turborepo monorepos. 

I've read both your blog post and the readme in this repo and, even though I do understand the problem, I'm having a hard time using this to set up Firebase for my needs.

Imagine the following example monorepo:

```
turbo.json
package.json
apps/
    nextjs/
        package.json
        src/
    another/
        package.json
        src/
packages/
    api/
        package.json
        src/
   ui/
       package.json
       src/
tooling/
    firebase/
      firebase.json
      package.json
```

Assuming the scenario described above, I'd like to be able to:
  - deploy the `apps/nextjs` app to Firebase (hosting + functions)
  - deploy the `packages/api` package to Firebase (this package contains our backend API in form of cloud functions)
  - `tooling/firebase` simply contains emulator configuration and possibly other firebase config files to be used across the repo (basically Firebase config that is not deployed, per se)
  
Is this scenario a possibility? How would I go about configuring this? I'm assuming this means multiple "target packages"?

Thanks in advance for the help!

P.S.: I'm using `pnpm`, if that matters

**Comment by 0x80** [comment]
Hi @matallui I do not have time to get into this now, but I have been working on a an example monorepo featuring isolate-package. I have just uploaded the initial commit, but it still needs more work and documentation before I announce it.

You can have a look at it [here](https://github.com/0x80/mono-turbo-next-fire)

In short, I think your firebase files belong to a package. You can have multiple packages deploy to firebase if you want, but in a simple project you don't need more then one. I don't see a reason to not co-locate your firebase config with that package, but if you have one try to explain it to me.

**Comment by matallui** [comment]
Btw, I took a look at your monorepo example and it looks similar to what I'd want to do, so thanks for sharing that!

Not sure what you meant by only deploying 1 package per project to firebase. It looks like you are deploying both `services/api` and `services/functions` to Firebase and they're all part of the same project (i.e., same monorepo).

Maybe I misunderstood your statement.

**Comment by 0x80** [comment]
Yes I meant to say that you can deploy from multiple packages to the same project, but in a typical project you would probably only have one package targeting Firebase. 

If you do use multiple, like in my example, then have to choose where to put things like storage and database rules, because the other packages will be "functions only".

**Comment by matallui** [comment]
Gotcha! I'll play with it and see what I can come up with. Your example monorepo helps a lot, so thanks again for the help!!
