### ISSUE TITLE
Asking for all dependencies when using node-linker=hoisted

### ISSUE THREAD

**Issue by mordonez-me** [0x80/isolate-package#38]
Hello everyone, I am just reporting this behavior and asking if this is expected.

![image](https://github.com/0x80/isolate-package/assets/2242042/2f1f48fd-36dc-40b4-989b-1f27d18ac8ca)

This is happening for every transitory dependency, is this normal since hoisted is enabled?

**Comment by 0x80** [comment]
I don't have experience with that setting, but `isolate` is copying the .npmrc file to the output directory, and I'm not entirely sure that is desirable, so maybe you can try to remove it from the output before deploying?

At what point are you seeing this error?

**Comment by mordonez-me** [comment]
Yeah it's weird with this config but it made me realize something, if you have set patches and resolutions in the root package.json, they are not added to the isolated package.json, so the only option for now (like adding all libraries) is add the same config in firebase functions package.json.

**Comment by 0x80** [comment]
Thanks. It seems I indeed failed to consider including "resolutions" in the output manifest. That should be an easy fix.

 What is "patches" I'm not familiar with it.

**Comment by 0x80** [comment]
I have tested the manifest output and the resolutions field is preserved. Only scripts are omitted by default, and there are now configuration options to pick or omit certain scripts. 

I am going to close this, assuming your issue is not related to isolate-package, but feel free to reopen this if you can provide more details and context.

**Comment by mordonez-me** [comment]
Hi, I think it is preserved when the same project has it but (one of the repos in the monorepo) but if the root project has it (which is the only way to make it work), it's not preserved.

**Comment by 0x80** [comment]
Ah, right. Indeed, the root manifest is not used in any way currently.

Have you tried deploying with lockfile included? I don't know much about resolutions, but I would expect the lockfile to contain all the information about resolved packages.
