### ISSUE TITLE
Getting a ERR_MODULE_NOT_FOUND during firebase deploy

### ISSUE THREAD

**Issue by 1jmj** [0x80/isolate-package#47]
Using your demo mono-ts repo as an example, I have attempted to integrate my own library package and deploy firebase functions. On deploy, it makes the isolate folder but as soon as firebase analyses the folder it gives me a `ERR_MODULE_NOT_FOUND` for one of the external packages in the library package. 

```
info Isolate completed at /mono-ts/services/fns/isolate
✔  functions: Finished running predeploy script.
i  functions: preparing codebase fns for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase fns to determine what to deploy
Serving at port 8449

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ssh2-sftp-client' imported from /mono-ts/services/isolate/dist/index.js
Did you mean to import ssh2-sftp-client@10.0.3/node_modules/ssh2-sftp-client/src/index.js?
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by 0x80** [comment]
I think there must be something wrong with the way you configured things. Please read the section on [prerequisites](https://github.com/0x80/isolate-package?tab=readme-ov-file#prerequisites)

If you then still can't make it work, please share some additional info about how you declared it as a dependency, and share your package manifest.

**Comment by 0x80** [comment]
In addition, you can follow the [troubleshooting instructions](https://github.com/0x80/isolate-package?tab=readme-ov-file#troubleshooting) and inspect the output in the isolate directory.

**Comment by 1jmj** [comment]
Thanks for the quick reply, I'm pretty sure its all set up right. I've tried with the firebase-tools-with-isolate package too, and same result.

It works fine so long as my @repo/sftp method doesn't reference the dependent package (ssh2-sftp-client) but as soon as it does firebase won't deploy.

Firebase manifest
```
{
  "name": "functions",
  "version": "0.0.0",
  "type": "module",
  "main": "./dist/index.js",
  "module": "./dist/index.js",
  "files": [
    "dist",
    ".env.*"
  ],
  "scripts": {
    "type:check": "tsc --noEmit",
    "build": "tsup-node",
    "build:watch": "tsup-node --watch",
    "emulate": "firebase emulators:start --only functions",
    "dev": "run-p build:watch emulate",
    "lint": "eslint . --max-warnings 0",
    "deploy": "firebase deploy --only functions"
  },
  "engines": {
    "node": "20"
  },
  "dependencies": {
    "@google-cloud/functions-framework": "^3.3.0",
    "@repo/sftp": "workspace:*",
    "firebase-admin": "^11.8.0",
    "firebase-functions": "^4.3.1"
  },
  "devDependencies": {
    "@repo/eslint-config": "workspace:*",
    "@repo/typescript-config": "workspace:*",
    "@types/node": "^20.11.17",
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^3.1.0",
    "firebase-tools": "^13.3.0",
    "isolate-package": "^1.9.4",
    "tsup": "^8.0.2",
    "typescript": "^5.3.3"
  },
  "private": true
}
```

@repo/sftp
```
{
  "name": "@repo/sftp",
  "version": "0.0.0",
  "type": "module",
  "types": "./src/index.ts",
  "exports": {
    ".": "./src/index.ts"
  },
  "files": [
    "src"
  ],
  "scripts": {
    "?build": "This package is links directly to its source files",
    "type-check": "tsc --noEmit",
    "test": "vitest",
    "coverage": "vitest run --coverage ",
    "lint": "eslint . --max-warnings 0"
  },
  "license": "MIT",
  "dependencies": {
    "firebase-admin": "12.0.0",
    "ssh2-sftp-client": "^10.0.3"
  },
  "devDependencies": {
    "@types/node": "^20.11.16",
    "@types/ssh2-sftp-client": "^9.0.3",
    "dotenv": "^16.4.1",
    "npm-run-all": "^4.1.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3"
  }
}
```
packages/sftp/src/index.ts
`export const echo = (what: string) => `you said ${what}`;` works and deploys fine

adding `import Client from "ssh2-sftp-client";` causes the ERR_MODULE_NOT_FOUND during firebase deploy

**Comment by 0x80** [comment]
You are not importing from your internal dependency it seems:

`import Client from "ssh2-sftp-client";`

should be

`import Client from "@repo/sftp";

**Comment by 1jmj** [comment]
apologies, that has confused things.

In my fns firebase project, I import like this:

```
import {
  type ConnectionInfo,
  echo,
  fetchSftpFiles,
} from "@repo/sftp";

export const helloWorld = onRequest((request, response) => {
  const connectionInfo: ConnectionInfo = {...};
  fetchSftpFiles(connectionInfo);
  response.send(echo("Hello from Firebase!"));
});
```

adding `import Client from "ssh2-sftp-client";` and a method to call it to my packages/sftp/src/index.ts causes the ERR_MODULE_NOT_FOUND during firebase deploy

**Comment by 0x80** [comment]
Weird. I don't see the problem yet. But isolate deals with internal dependencies and not external, so I don't know yet how it can be related.

Did you inspect the output of the isolate directory? Is the package.json file there (in ./package/sftp listing the "ssh2-sftp-client" dependency?

**Comment by 1jmj** [comment]
Yes, it's showing that dependency in the `isolate` directory.

**Comment by 1jmj** [comment]
I managed to recreate a working and non-working example in your mono-ts.  I think it's to do with the build that backend does but common doesnt because it's linked directly.

So, adding the following code to @repo/backend results in a working deployable firebase functions:

modify `packages/backend/src/utils/index.ts`
```
import Client from "ssh2-sftp-client";
export function getClient() {
  return new Client();
}
```

and import it into the `services/api/src/server.ts`
```
import { getClient } from "@repo/backend";
const test = getClient();
```

Works...


But modify, 
`packages/common/src/index.ts`
```
import Client from "ssh2-sftp-client";
export const getClient = () => new Client();
```
and import it into the `services/api/src/server.ts`
```
import { getClient } from "@repo/common";
const test = getClient();
```

Does NOT work....

It's re-createable with any external package like `dayjs` for example.

**Comment by 0x80** [comment]
I don't have time to look into it now, but I suspect it has something to do with the fact that you reference the source from @repo/sftp directly without building/bundling. I didn't test this method extensively, because my own projects use bundling on all packages.

What you could try as a workaround maybe is to add "ssh2-sftp-client" as a dependency to the firebase service, or add bundling to @repo/sftp.

**Comment by 0x80** [comment]
@1jmj I was able to reproduce the problem, and it seems the internal packages strategy is mainly interesting if your consuming app is something like Next.js which has a transpilePackages setting that will transpile the source and bundle its dependencies .

If the consuming app is using TSUP like services/api, then the import is merely treated as a folder of source files, and dependencies from common also need to be installed there, which makes the strategy a lot less attractive I think.

I've updated the code and the readme. See https://github.com/0x80/mono-ts/commit/d0186fea48d41667203b5bd46addcde84033c0b3
