### ISSUE TITLE
pnpm overrides are breaking gcp deployments

### ISSUE THREAD

**Issue by milo-** [0x80/isolate-package#55]
I'm trying to deploy to firebase, but it fails if there are pnpm overrides in the root package.json.

```Build failed with status: FAILURE and message: installing pnpm dependencies: (error ID: 8622936f):
ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "overrides" configuration doesn't match the value found in the lockfile
```

To workaround this, I've duplicated the overrides in each apps package.json, but this does give the warning `The field "pnpm" was found in /XXX/apps/my-app/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.`

It would be awesome if isolate-package could copy the pnpm.overrides from the root package.json to the isolate/package.json file, so I don't need to manually copy them.

Finally, thanks @0x80 for building isolate-package 🙌 🙌

**Comment by 0x80** [comment]
@milo- Thanks for reporting. I have no experience using overrides, but it sounds like an easy fix so I will soon look into it.

**Comment by milo-** [comment]
Sure thing @0x80 

```
{
  "name": "XXX",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev",
    "lint": "turbo run lint",
    "format": "prettier --write \"**/*.{ts,tsx,md}\""
  },
  "dependencies": {},
  "devDependencies": {},
  "engines": {
    "node": "20",
    "pnpm": ">=3"
  },
  "packageManager": "pnpm@8.6.7",
  "pnpm": {
    "overrides": {
      "lodash@<4.17.11": ">=4.17.11",
      "lodash@<4.17.5": ">=4.17.5",
      "minimatch@<3.0.2": ">=3.0.2",
      "lodash@<4.17.12": ">=4.17.12",
      "lodash@<4.17.21": ">=4.17.21",
      "minimatch@<3.0.5": ">=3.0.5",
      "undici": "^5.28.3",
      "jose@>=3.0.0 <=4.15.4": ">=4.15.5",
      "@google-cloud/firestore": "7.3.1"
    }
  }
}
````

**Comment by 0x80** [comment]
Thanks, I'm going to assume that we can ditch the whole pnpm field then, unless you tell me otherwise. I don't know what other things can be part of it, or what it will be used for in the future, but I think it's probably safer to omit it completely if we don't know.

**Comment by milo-** [comment]
I think the two options that will work are:

1. Copy pnpm.overrides from the root package.json into isolate/package.json
2. Remove overrides from isolate/pnpm-lock.yaml

**Comment by milo-** [comment]
Yeah I think so 👍
