### ISSUE TITLE
There are types at 'isolate-package/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports".

### ISSUE THREAD

**Issue by mathieu-bour** [0x80/isolate-package#58]
In order to solve problem described in #56,  I built a script to handle my isolation process. However, TypeScript refuses to import the `isolate-package` types.

Here is the full error:

```
Could not find a declaration file for module 'isolate-package'. '[workspace]/node_modules/.pnpm/isolate-package@1.10.1/node_modules/isolate-package/dist/index.mjs' implicitly has an 'any' type.
  There are types at [workspace]/apps/api/node_modules/isolate-package/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'isolate-package' library may need to update its package.json or typings.ts(7016)
```

I am using isolate-package v1.10.1.

<details>
<summary>The script:</summary>

```ts
import { execSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { isolate } from 'isolate-package';
import { rimraf } from 'rimraf';
import { build as tsup } from 'tsup';
import tsupConfig from '../tsup.config';

const isolateDirName = 'isolate';

await rimraf(['dist', isolateDirName]);
await tsup(tsupConfig);
await isolate({
  isolateDirName,
});

// Copy the overrides from the root workspace to the isolate workspace
const rootPackageJson = JSON.parse(await readFile('../../package.json', 'utf-8'));
const isolatePackageJson = JSON.parse(await readFile('package.json', 'utf-8'));
isolatePackageJson.pnpm = { ...isolatePackageJson.pnpm, overrides: rootPackageJson.pnpm.overrides };

await writeFile('isolate/package.json', JSON.stringify(isolatePackageJson, null, 2));
execSync('pnpm install --lockfile-only', { cwd: isolateDirName, stdio: 'inherit' });
execSync('zip -r ../dist/function.zip ./*', { cwd: isolateDirName, stdio: 'inherit' });

await rimraf([isolateDirName]);
```

</details>

<details>
<summary>My tsconfig.json:</summary>

```json
{
  "extends": "@tsconfig/strictest/tsconfig.json",
  "compilerOptions": {
    "outDir": "dist",
    "strict": true,

    "allowJs": false,
    "checkJs": false,
    "noEmit": true,
    "allowImportingTsExtensions": true,

    "forceConsistentCasingInFileNames": true,
    "verbatimModuleSyntax": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true,

    "exactOptionalPropertyTypes": false,

    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",

    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["**/*.ts"],
  "exclude": ["node_modules"]
}
```

</details>

The fix is fairly easy: add explicit types to the `package.json` `exports`:

```diff
   "type": "module",
   "types": "./dist/index.d.ts",
   "exports": {
-    ".": "./dist/index.mjs"
+    ".": {
+      "import": "./dist/index.mjs",
+      "types": "./dist/index.d.ts"
+    }
   },
   "files": [
     "dist",

```

Happy to submit a PR.

**Comment by 0x80** [comment]
Thanks for reporting. I wasn't aware that `exports.types` was still needed when `types` is already defined in the root. I will change it soon, and if you like you can also submit a PR.

Do you happen to have a link to some documentation where this requirement is described?

**Comment by 0x80** [comment]
I don't see how this would be related to #56, since that is a runtime error. Can you elaborate on that?

**Comment by 0x80** [comment]
@mathieu-bour what is your setting for "moduleResolution" in Typescript? I'm trying to figure out why you are having trouble with the types, because my applications don't have this problem.

**Comment by mathieu-bour** [comment]
@0x80 my `moduleResolution` is `Bundler`. fyi I added the full tsconfig in the first issue.

**Comment by 0x80** [comment]
@mathieu-bour Sorry I missed them. In my browser the code blocks were collapsed and I didn't notice them.

**Comment by 0x80** [comment]
@mathieu-bour I had to change it to something else because your proposal broke the integration in `firebase-tools-with-isolate`. In the latest version I just do `exports: "./dist/index.mjs"`. I hope this works for you, and seems to be the correct way for pure ESM packages.

If it doesn't work, please tell me more about how you're executing your script.

**Comment by 0x80** [comment]
@mathieu-bour  did you meant to link #55 instead #56? Seems like that's where the confusion came from.
