### ISSUE TITLE
Isolate seem to be not copying the `.env` file

### ISSUE THREAD

**Issue by vajahath** [0x80/isolate-package#59]
Isolate seem to be not copying the `.env` file. (but it copies `.env.local` and `.env.staging` in my case)

According to [firebase docs](https://firebase.google.com/docs/functions/config-env?gen=2nd#deploying_multiple_sets_of_environment_variables),

> If you need an alternative set of environment variables for your Firebase projects (such as staging vs production), create a .env.<project or [alias](https://firebase.google.com/docs/cli#project_aliases)> file and write your project-specific environment variables there. The environment variables from .env and project-specific .env files (if they exist) will be included in all deployed functions.

(Also see the tabled example from the docs to see how the envs are inherited)

In short, `.env` is a valid env config for firebase functions.

**Comment by 0x80** [comment]
@vajahath did you add it to the "files" field in the manifest? Those define what is picked up as part of the pack/unpack process. Also see https://github.com/0x80/isolate-package?tab=readme-ov-file#define-files-field-in-each-package-manifest

**Comment by vajahath** [comment]
Yep. I missed this. Thank you for pointing out. Closing this.
