### ISSUE TITLE
Option to prevent move of node_modules for NPM

### ISSUE THREAD

**Issue by bmcbarron** [0x80/isolate-package#82]
I use Windows, and I often have processes running that have open files in `node_modules` which prevent it from being moved. Rather than always killing those processes, I did some experimentation with a fork of `isolate-package`. Interestingly, skipping the move altogether seems to work fine. Arborist found the dependent packages, even though they was several levels above the isolate folder.

Could we add a configuration option which disables the move?

Thanks!

**Comment by 0x80** [comment]
That is great news, but if the move is not necessary than my findings seem incorrect and I think we can just take that part out completely, no? Or do you still see a valid use-case for moving the folder?

**Comment by bmcbarron** [comment]
It's such a complex ecosystem, that I'd be wary of outright removing it, especially if you found otherwise at some point. At the most, I would add an option and have it default to not moving. That way folks who are depending on it can re-enable easily. If enough time goes by without hearing from those folks, then pull the trigger and remove it completely. WDYT?

**Comment by 0x80** [comment]
@bmcbarron I have released 1.16.0 where I have taken out the code for moving node_modules.

It's possible that older versions of NPM still need this, but I think people can just upgrade if that's the case :)
