### ISSUE TITLE
If workspaces is set to an object, we get a crash.

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [0x80/isolate-package#9]
I have this object as my workspaces setting in my root package.json

`	"workspaces": {
		"packages": [
			"apps/*",
			"packages/*"
		],
		"nohoist": [
			"**/ts-node"
		]
	},
`

This causes an error on this line: https://github.com/0x80/isolate-package/blob/main/src/helpers/create-packages-registry.ts#L61, as flatMap is not defined on an object. 

I have fixed my issue by providing it trough setting `workspacePackages` in the config manually. Thanks a lot for the project!

You rock!

**Comment by 0x80** [comment]
Hi @JoachimKoenigslieb thanks for reporting, and for the kind words :) I will look into it, hopefully soon, but I'm travelling atm.
